# Sles Docker Images  
rmt_image: 
db_image: artifacts.ruv.de/mariadb:10.2
nginx_image: artifacts.ruv.de/nginx

# Docker Vars 
db_volume: /srv/www/rmt/public/
rmt_command: /bin/bash -c 'bundle.ruby2.5 exec rails db:migrate && bundle.ruby2.5 exec rails s -b rmt'
nginx_root_volume: /public:/var/www/
nginx_conf_volume: /tmp/default.template
- ./public:/var/www/
      - ./nginx/default.conf:/tmp/default.template


# Environment Variables 
MYSQL_ROOT_PASSWORD=toor
MYSQL_DATABASE=rmt
MYSQL_USER=rmt
MYSQL_PASSWORD=rmt
MYSQL_HOST=db
SECRET_KEY_BASE=8ea53ad3bc6c03923e376c8bdd85059c1885524947a7efe53d5e9c9d4e39861106ffd6a2ece82b803072ed701e6c960bade91644979e679416c5f255007237ae
EXTERNAL_PORT=8080
SCC_USERNAME=6624895
SCC_PASSWORD=27fb8e31a6





